# Site settings
baseurl = "https://taiwan2020.satrdays.org/" # Change this to the base url after netlify deploy, e.g. "https://cardiff2019.satrdays.org/"
languageCode = "zh-tw"  # "en-us"
title = "satRday Taiwan"
theme = ["hugo-satrdays-theme", "hugo-agency-theme"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Disable taxonomies that are not used https://discourse.gohugo.io/t/found-no-layout-for-taxonomyterm-language-en-output-format-html/16376
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "satRday in Taiwan"
  description = "R conference in Taiwan"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = ["css/satrday.css"]
  custom_js  = []
  favicon    = "img/favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "satRday"
    # Optional logo as brand stored in img/
    logo = "logo.png"
    services = "About"
    portfolio = "Talks"
    #eventbrite = "Register"
    #schedule = "Schedule"
    about = "Schedule"
    team = "Team"
    contact = "Get involved"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "http://satrdays.org/"
      name = "satRdays.org"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "satRday Taiwan | May 16, 2020"
    subtitle = "A conference for users of the R Language"
    bg = true
    buttonText = "Tell me more"


  # About [Services] section
  [params.services]
    enable = true
    title = "About"
    subtitle = "Conference Details"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-clock-o"
      title = "What's SatRday"
      description = "R-focused Conference on R and its applications"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-laptop"
      title = "Details"
      description = "2020/05/16 ＠ Tamkang University"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-graduation-cap"
      title = "Learning"
      description = "Learn from your Peers and Experienced Professionals"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-users"
      title = "Community Lead"
      description = "R-Ladies Taipei / Taiwan R User Group"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-money"
      title = "Affordable"
      description = "Free"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-universal-access"
      title = "Accessible"
      description = "Inclusive, Supportive and Respectful Environment"
      url = "#"

  # Register section
  # You only need ONE of these active
  [params.tito]
    enable = false
    title = "Register"
    bg = true
    accountevent = "ultimateconf/2013"
      # Go to https://ti.to/ and find the account (under your user) and event pair string e.g. "cardiff-satrday/2018"
      # include botht the account and event in a string, seperated by /, with no spaces

  [params.eventbrite]
    enable = false
    title = "Register"
    bg = true
    eid = "32416000129" 
      # Go to https://www.eventbrite.co.uk/support/articles/en_US/How_To/how-to-sell-eventbrite-tickets-registrations-on-your-website-using-embeddable-widgets?lg=en_GB 
      # Follow instructions to discover your 'Website Integration' embeddable iframe
      # Take ONLY the numeric string between "eid=" and "&ref=etckt"
      # Supply this string as the value to `eid` above

  [params.tickettailor]
    enable = false
    title = "Register"
    bg = true
    eventviewid = "162430"
      # Go to www.tickettailor.com and open your event page
      # Note the number at the end of the url e.g. https://www.tickettailor.com/event/view/id/162430
      # Supply the number ONLY in `eventviewid`
  
  # Call for papers section
  [params.callforpapers]
    enable = false
    title = "Call For Papers"
    bg = false
    CfSpage = "/satrday-taiwan-2020"
      # Go to Organizer > My Events > Dashboard and copy the "CfS Page" string into the `CfSpage` value
    dates = "09 Aug - 21 Sep 2018"

  # Talk [Portfolio] section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Keynote Speakers"
    subtitle = ""
    bg = true

    #[params.portfolio.modal]
     # client = "Client"
      #date = "Date"
      #category = "Category"
      #buttonText = "Close project"

  # Schedule section
  [params.schedule]
    enable = false
    title = "Schedule"
    bg = false

  # Important Dates [About] section
  [params.about]
    enable = true
    title = "Important Dates"
    subtitle = "Be prepared!"
    endpoint = "May 16<br>SatRday Conference"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "start.png"
      date = "March 1"
      title = "開放報名"
      description = "Free"

    #[[params.about.events]]
    #  img = "2.jpg"
    #  date = "Second Date"
    #  title = "Early Bird Ticket Sales"
    #  description = "Early round of tickets now available at discount"

    # [[params.about.events]]
    #  img = "3.jpg"
    #  date = "Third Date"
    #  title = "Call For Papers"
    #  description = "Submissions for speakers are now open!"

    # [[params.about.events]]
    #  img = "4.jpg"
    #  date = "Fourth Date"
    #  title = "Call For Papers Ends"
    #  description = "Cut off date for speaker submissions"
  
  # Location section
  [params.location]
    enable = true
    title = "Location title"
    bg = true
    iframesrc = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3610.863827216273!2d121.44511211487061!3d25.174075438816168!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442aff8c1544bdb%3A0x1dcf4f494b3362b!2sTamkang%20University!5e0!3m2!1sen!2stw!4v1577937288324!5m2!1sen!2stw"

  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    # center = true
    title = "Team"
    subtitle = "The people putting it together"
    bg = false
    description = ""
    # speakers = "Speakers"
    

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "kristen.jpg"
      name = "Kristen Chan"
      position = "Organizer"
      reportsTo = ""
      # For bio markdown and even multiline strings are available.
      social = [
        ["fa-github", "https://github.com/kristenchan"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
     img = "amy.jpg"
     name = "Amy Tzu-Yu Chen"
     position = "Organizer"
     reportsTo = ""
     # For bio markdown and even multiline strings are available.
     social = [
        ["fa-twitter", "https://twitter.com/amy17519"],
        ["fa-github", "https://github.com/amy17519"],
        ["fa-linkedin", "http://linkedin.com/in/amy17519"]
    ]

    [[params.team.members]]
     img = "angie.jpg"
     name = "Angie Hsu"
     position = "Organizer"
     reportsTo = ""
     # For bio markdown and even multiline strings are available.
     social = [
        ["fa-linkedin", "#"]
    ]

    # [[params.team.members]]
    #  img = "faceholder.png"
    #  name = "Organiser Name 2"
    #  position = "Organiser Position 2"
    #  social = [
    #    ["fa-twitter", "#"],
    #    ["fa-github", "#"],
    #    ["fa-linkedin", "#"]
    #  ]

  # Client section
  [params.clients_list]
    enable = true
    # Possibility to center items
    #center = true
    # Optional client title specifying the involvement
    title = "Sponsors"
    bg = true

    # All the clients' logos are stored under 'static/img/logos'.
    # Replace them with your clients's logos.
    # Suggestion: .svg in the size of 280px*80px looks good
    [[params.clients]]
      logo = "microsoft.png"
      link = "#"

    [[params.clients]]
      logo = "rstudio.png"
      link = "#"

  
  [params.diversity]
    enable = true
    title = "Code of Conduct"
    bg = true

  # Contact section
  [params.contact]
    enable = false
    title = "Contact us"
    subtitle  = "Lorem ipsum dolor sit amet consectetur."
    buttonText = "Send message"
    # netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "your@email.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    [params.contact.captcha]
      # sitekey = ""

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/satrdays_org"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-github"
      link = "https://github.com/satRdays"
      title = "GitHub"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
